# Generated by Django 4.1 on 2022-11-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_company_name_job_contact_info_alter_job_creator'),
        ('users', '0002_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
