# Generated by Django 4.1 on 2022-10-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='creater',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='title',
        ),
    ]
