# Generated by Django 4.1 on 2022-11-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_company_name_job_contact_info_alter_job_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
